### ISSUE TITLE
Compatibility with Symfony 3.1

### ISSUE THREAD

**Issue by rpander93** [VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle#13]
Hi,

Could you update the composer file to allow for Symfony v3.1?

Thanks!

**Comment by VasekPurchart** [comment]
Hi, I believe the [composer.json](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/blob/master/composer.json#L16) does not forbid Symfony 3.1. It was released as [0.4](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/releases/tag/0.4), are you sure you are using an up-to-date version? Btw I am using this on my projects with SF 3.1 fine :)

**Comment by rpander93** [comment]
I did a "composer require vasek-purchart/doctrine-date-time-immutable-types-bundle" but that gave me 0.2. I manually set it to ^0.4 and that did the trick. Thanks!

**Comment by VasekPurchart** [comment]
Np, glad you solved it :)
