### ISSUE TITLE
Update library to 0.4

### ISSUE THREAD

**Issue by jonny-no1** [VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle#16]
Update [VasekPurchart/Doctrine-Date-Time-Immutable-Types](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types) to 0.4

**Comment by VasekPurchart** [comment]
Yep, working on it :)

**Comment by VasekPurchart** [comment]
Released as [0.4.2](https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types-Bundle/releases/tag/0.4.2)
